name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

permissions:
  contents: write   # IMPORTANT: allow GitHub Action to commit files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: saitejakm
          template: classic
          config_timezone: Asia/Kolkata

          # Contribution scraping
          base: header, activity
          repositories_affiliations: owner, collaborator, organization_member

          # Output file
          filename: github-metrics.svg

          # Show PRs, commits, etc
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 365

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update GitHub metrics" || echo "No changes"
          git push
